### ISSUE TITLE
Using Flow

### ISSUE THREAD

**Issue by BrentHawk** [markjay4k/YOLO-series#10]
When trying to use flow to load an mp4 video to process I get the following error:

It looks like it's trying to use a camera and not load the file (just a guess).

![image](https://user-images.githubusercontent.com/36515854/38463068-ded60b78-3ab6-11e8-8a1f-75830c6ac12b.png)

**Comment by markjay4k** [comment]
looks like an issue with darkflow not selecting the video correctly. are you trying to run yolo on a video and running from the terminal?

**Comment by BrentHawk** [comment]
Thanks for the response Markjay4k!!

Correct – I am trying to run yolo on the video from the terminal.

Command syntax below:

Python flow –model cfg/yolo.cfg –load bin/yolo.weights  --demo people.mp4 –gpu 1.0 –saveVideo

The “people.mp4” video file is located in the base “darkflow directory”  (i.e. home/bdh/darkflow).

Any ideas?

Brent

**Comment by markjay4k** [comment]
try running the command without python in front. so just

```shell
flow --model cfg/yolo.cfg --load bin/yolo.weights --demo people.mp4 --gpu 1.0 --saveVideo
```

**Comment by BrentHawk** [comment]
Ok thanks!  I will try it once I fire up my VM…

Brent

**Comment by InnovativeCoder** [comment]
is this resolved, it is showing me an error
Parsing ./cfg/yolo.cfg
Parsing cfg/yolo.cfg
Loading bin/yolo.weights ...
Traceback (most recent call last):
  File "/Users/DBRSJ/anaconda/envs/tf_env/bin/flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/dark/darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/Users/DBRSJ/anaconda/envs/tf_env/lib/python3.6/site-packages/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
**AssertionError: expect 203934260 bytes, found 248007048**
please see if this can be corrected.

**Comment by advset** [comment]
(This was written May 25th)
I'm new to this field and just a user (opencv - python),
this is my first time trying to use Yolo and I face the similar issue with Innovative Coder

I'm using python 3.6.5 (anaconda environment), opencv 3.4.1,  tensorflow 1.8.0, gpu with cuda toolkit 9.0

Thank you very much for your help.

(Edited may 26th)
I have solved my own case. Turns out that we need to use the same version for yolo configuration model (inside cfg folder) and for yolo weight file (to be put inside bin folder)

Thank you =)
