### ISSUE TITLE
Cant load the model 

### ISSUE THREAD

**Issue by kkwong95** [markjay4k/YOLO-series#20]
Sorry everyone, can anyone give me some input about this. 
I use window 10 and followed mark jay atom setup. Somehow, I still get this error

Traceback (most recent call last):
  File "C:\Users\user\Downloads\darkflow-master (new)\testing.py", line 13, in <module>
    tfnet = TFNet(option)
  File "C:\Users\user\Downloads\darkflow-master (new)\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\user\Downloads\darkflow-master (new)\darkflow\dark\darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "C:\Users\user\Downloads\darkflow-master (new)\darkflow\dark\darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/yolov2.weights not found

I had put the right directory but still get this error. I read a solution which mentioned window permission access. How can I do that? In atom environment or just the file

**Comment by kkwong95** [comment]
I solved the problem. I run with profile (directory to darkflow folder) rather than click run.
