### ISSUE TITLE
_tkinter_tkapp has no attribute setGeometry

### ISSUE THREAD

**Issue by techied** [markjay4k/YOLO-series#3]
Stacktrace is as follows: 
`Traceback (most recent call last):
  File "C:\Users\Paperspace\Downloads\darkflow-master\new_model_data\draw_box.py", line 52, in <module>
    mngr.window.setGeometry(250, 120, 1280, 1024)
  File "C:\Program Files (x86)\Python36-32\lib\tkinter\__init__.py", line 2095, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'setGeometry'`

What could be causing this?

**Comment by paulbf87** [comment]
same issue with me

**Comment by markjay4k** [comment]
you can remove the 2 lines for setGeometry. they are not needed

**Comment by zubairahmed-ai** [comment]
I am facing the same issue here

**Comment by noorkhokhar99** [comment]
i am see this error python version which we used old type of version and code will be 3.6 in python.
so you can remove one line  # mngr.window.setGeometry(250, 120, 1280, 1024).
Enjoy!

**Comment by joanqwerty** [comment]
write this
mngr.window.setGeometry = (250, 120, 1280, 1024)

**Comment by biswajit-hub** [comment]
@joanqwerty Thanks
