### ISSUE TITLE
HTTP Error 400: Bad Request in Part 5 Get Images

### ISSUE THREAD

**Issue by bhaveshpadharia** [markjay4k/YOLO-series#39]
`"/home/bhavesh/Object Detection/env/bin/python" "/home/bhavesh/Object Detection/YOLO-series/part5 - get_images.py"
Traceback (most recent call last):
  File "/home/bhavesh/Object Detection/YOLO-series/part5 - get_images.py", line 41, in <module>
    links = get_links(search_name)
  File "/home/bhavesh/Object Detection/YOLO-series/part5 - get_images.py", line 21, in get_links
    json_string = ulib.urlopen(request).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
`

**Comment by DynamicCodes** [comment]
Any solutions as of now??
