### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by MahdiGuermani** [markjay4k/YOLO-series#4]
While i run this script:

import os
import urllib.request as ulib
from bs4 import BeautifulSoup as Soup
import json

url_a = 'https://www.google.com/search?ei=1m7NWePfFYaGmQG51q7IBg&hl=en&q={}'
url_b = '\&tbm=isch&ved=0ahUKEwjjovnD7sjWAhUGQyYKHTmrC2kQuT0I7gEoAQ&start={}'
url_c = '\&yv=2&vet=10ahUKEwjjovnD7sjWAhUGQyYKHTmrC2kQuT0I7gEoAQ.1m7NWePfFYaGmQG51q7IBg'
url_d = '\.i&ijn=1&asearch=ichunk&async=_id:rg_s,_pms:s'
url_base = ''.join((url_a, url_b, url_c, url_d))

headers = {'User-Agent': 'Chrome/41.0.2228.0 Safari/537.36'}

def get_links(search_name):
    search_name = search_name.replace(' ', '+')
    url = url_base.format(search_name, 0)
    request = ulib.Request(url, None, headers)
    json_string = ulib.urlopen(request).read()
    page = json.loads(json_string)
    new_soup = Soup(page[1][1], 'lxml')
    images = new_soup.find_all('img')
    links = [image['src'] for image in images]
    return links

if __name__ == '__main__':
    search_name = 'fidget spinner'
    links = get_links(search_name)

for link in links:
    print (link)

i got this error:

Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\darkflow-master\cam.py", line 29, in <module>
    links = get_links(search_name)
  File "C:\Users\lenovo\Desktop\darkflow-master\cam.py", line 20, in get_links
    page = json.loads(json_string)
  File "C:\Users\lenovo\Anaconda31\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[Finished in 1.669s]
![sans titre](https://user-images.githubusercontent.com/23280687/36973255-7bc877c2-2072-11e8-860e-3464f9f57724.png)

help please !

**Comment by markjay4k** [comment]
I've seen this error when running this code using python3.5.
Can you try using python3.6 to run?

**Comment by RossMelbourne** [comment]
I received this error after fixing the URL issue.  However I am now getting a different error.
First I believe the Google Image search URL in the code is no longer a valid URL.  I think you need to do the Google image search manually and copy and use the new URL in your code.  Second, I think the string passed to json.loads needs to be converted to utf-8.  Here is the line of code that needs to change: 
page = json.loads(json_string.decode("utf-8")) 
See if you get the same error as me from the line above:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
