### ISSUE TITLE
where i should save the .py script?

### ISSUE THREAD

**Issue by mursyidinadnan** [markjay4k/YOLO-series#6]
i try using other python application and i save the .py file in the same directory of darkflow, but the load model is always filed and always get error like this

> AssertionError: bin/yolo.weights not found
Traceback (most recent call last):
  File "C:\Users\Mladen Stokev\Anaconda3\pkgs\pywin32-222-py36hfa6e2cd_0\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 326, in RunScript
    exec(codeObject, __main__.__dict__)
  File "C:\dark\darkflow\ngetestpy.py", line 6, in <module>
    tfnet = TFNet(options)
  File "C:\dark\darkflow\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\dark\darkflow\darkflow\dark\darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "C:\dark\darkflow\darkflow\dark\darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/yolo.weights not found

where i should place the .py file? please if you have answer thankyou

**Comment by markjay4k** [comment]
the error is for the weights not being found. You should have a ```bin``` directory in the ```darkflow-master``` directory. the weights need to go in there. The weights need to be downloaded from the yolo website.
