### ISSUE TITLE
part3-processing_video.py throws AssertionError: Image is not a np.ndarray

### ISSUE THREAD

**Issue by SpeedCoder5** [markjay4k/YOLO-series#8]
at end of video play

**Comment by markjay4k** [comment]
you could possibly add a try / except statement to handle this error

**Comment by abdulkalam1233** [comment]
cfg/tiny-yolo-voc-1c.cfg parsing newModel/annotations
Parsing for ['0'] 
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/bot/yolo/darkflowmaster/darkflow/cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/bot/yolo/darkflowmaster/darkflow/net/flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/bot/yolo/darkflowmaster/darkflow/net/yolo/data.py", line 97, in shuffle
    data = self.parse()
  File "/home/bot/yolo/darkflowmaster/darkflow/net/yolo/data.py", line 18, in parse
    dumps = pascal_voc_clean_xml(ann, meta['labels'], exclusive)
  File "/home/bot/yolo/darkflowmaster/darkflow/utils/pascal_voc_clean_xml.py", line 22, in pascal_voc_clean_xml
    annotations = glob.glob(str(annotations)+'*.xml')
  File "/usr/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.6/glob.py", line 55, in _iglob
    yield from _glob1(dirname, basename, dironly)
  File "/usr/lib/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 954, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 450, in _parse_sub
    not nested and (not items)))
  File "/usr/lib/python3.6/sre_parse.py", line 840, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.6/sre_parse.py", line 450, in _parse_sub
    not nested and (not items)))
  File "/usr/lib/python3.6/sre_parse.py", line 604, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range 1-0 at position 11

i am getting above error while running
**# python3 flow --model cfg/tiny-yolo-voc-1c.cfg --load bin/tiny-yolo-voc.weights --train --annotation newModel/annotations --dataset newmodel/o_char --epoch 300**

**Comment by flit86** [comment]
Hi Mark. Amazing video!!!! i have the same error: AssertionError: Image is not a np.ndarray. how i can fix it? Merci

**Comment by Jagan3534** [comment]
Traceback (most recent call last):
  File "C:/Users/jagan/Downloads/Automatic-Identification-and-Counting-of-Blood-Cells-master/Automatic-Identification-and-Counting-of-Blood-Cells-master/test.py", line 26, in <module>
    output = tfnet.return_predict(image)
  File "C:\Users\jagan\Downloads\Automatic-Identification-and-Counting-of-Blood-Cells-master\Automatic-Identification-and-Counting-of-Blood-Cells-master\darkflow\net\flow.py", line 83, in return_predict
    'Image is not a np.ndarray'
AssertionError: Image is not a np.ndarray


same for me can anyone help me please
